### PR TITLE
Change the Ef limit for HNSW when topk is large

### PR DESCRIPTION
**Pull request by xiaofan-luan**
see also #808

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@cydrain 
hi there, could you help to check the ut error on knowhere 2.0? thanks

**Comment by cydrain** [comment]
> @cydrain hi there, could you help to check the ut error on knowhere 2.0? thanks

Need update this test case:
```
2023-04-13T02:26:33.8975454Z /home/runner/work/knowhere/knowhere/tests/ut/test_config.cc:167: FAILED:
2023-04-13T02:26:33.8975801Z   CHECK( s == knowhere::Status::out_of_range_in_json )
2023-04-13T02:26:33.8976050Z with expansion:
2023-04-13T02:26:33.8976233Z   0 == 3
```

**Comment by liliu-z** [comment]
Let's check in a PR to remove these UT first then merge this in

**Comment by liliu-z** [comment]
@xiaofan-luan feel free to rebase this PR, UT is fixed.

**Pull request merged**
