### PR TITLE
Remove HNSW range search parameter range_k, use ef instead

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

before:
hnsw_range_search_old_1025

with this change:
hnsw_range_search_new_1025

### CODE REVIEW

**Comment by PwzXxm** [comment]
As we discussed in the meeting. Waiting for e2e tests pass.

**Comment by cydrain** [comment]
Since HNSW range search algorithm updated, the recall baseline need also be updated.
Will ask @yanliang567 to help on this.

**Pull request merged**
