### PR TITLE
Add API BruteForceSearch()

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

### CODE REVIEW

**Review by landyliu — COMMENTED** [review]
if this API is provided for segcore,  better put into a top direcotry,  for example , in index directory?

**Comment by cydrain** [comment]
> if this API is provided for segcore, better put into a top direcotry, for example , in index directory?

Each file under index directory is serving for a single index.
For this file BruteForce.cpp, it's not for a single index, it's a collection of faiss searching operations,
we cannot put it under index directory.

**Pull request merged**
