### PR TITLE
Replace Easylogging++ by Glog

### PR DESCRIPTION
**Pull request by jiaoew1991**
issue: https://github.com/milvus-io/milvus/issues/22789
/kind improvement

### CODE REVIEW

**Comment by liliu-z** [comment]
Ahaha Loves GLOG. Any chance to have some data about the performance comparison between them?

**Comment by jiaoew1991** [comment]
> 

The API of `spdlog` is quite different from what milvus and knowhere are currently using, so many changes need to be made 😅

**Comment by liliu-z** [comment]
> I'see raft depends spdlog(should be depends from rmm), so spdlog may also be a candidate. In my experience, spdlog has a similar interface to glog, and have better performance in multi-threads.

Good catch, and thanks for this suggestion.
For 3rdparty dependency, we will first keep what they are unless it affect the main project. From this point we don't have to align them.
For `spdlog`, thanks again for this proposal, and we can try to do some benchmark if time allows. If the result gives a strong support, we can definitely change all Milvus/Knowhere log system. All depends on cost&gain.

Always welcome suggestions

**Pull request merged**
